modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LordGrimmauld/createintegration/issues"
logoFile="createintegration_logo.png"
[[mods]]
modId="createintegration"
version="0.1.4b"
displayName="Create Integration"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-integration"
credits="Thanks to Alexander2907 for the textures"
authors="Grimmauld"
description='''
This mod adds an interface to convert mechanical energy provided from Create machinery to FE.
'''
[[dependencies.createintegration]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.createintegration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]" #keep updated
    ordering="NONE"
    side="BOTH"
[[dependencies.createintegration]]
    modId="create"
    mandatory=true
    versionRange="[mc1.14-0.2.2b,mc1.14-0.2.3]" #keep updated
    ordering="NONE"
    side="BOTH"
