modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/embeddedt/CreateChunkloading/issues"
logoFile="createchunkloading_logo.png"
license="LGPL-2.1 License"
[[mods]]
modId="createchunkloading"
version="0.3.0"
displayName="Create Chunkloading"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-integration"
credits="Thanks to LordGrimmauld for the original implementation of the chunkloader, used almost unmodified here."
authors="Grimmauld, embeddedt"
description='''This mod adds a block which loads the chunk it is in, even when moved by Create contraptions.'''
[[dependencies.createchunkloading]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.createchunkloading]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]" #keep updated
    ordering="NONE"
    side="BOTH"
[[dependencies.createchunkloading]]
    modId="create"
    mandatory=true
    versionRange="[mc1.18.1_v0.4a,)" #keep updated
    ordering="NONE"
    side="BOTH"
